'use strict';
const assert=require('assert');
const {modeBreakdown:b}=require('../../src/session/modeBreakdown');
const bw=b('BEDWARS',{games_played_bedwars:40,games_played_bedwars_1:40,four_three_games_played_bedwars:40},40);
assert.deepStrictEqual(bw.entries.map(e=>[e.label,e.games]),[['Solos',0],['Doubles',0],['Threes',40],['Fours',0],['4v4',0]]);
assert.equal(b('DUELS',{best_tnt_games_winstreak:10,classic_duel_kit_wins:8},10).status,'unavailable');
assert.equal(b('DUELS',{rounds_played:10,classic_duel_rounds_played:6,sumo_duel_rounds_played:4},10).entries.length,2);
assert.equal(b('DUELS',{bedwars_two_one_duels_rounds_played:6,bedwars_two_one_duels_rush_rounds_played:4},6).entries.reduce((n,e)=>n+e.games,0),6);
const sw=b('SKYWARS',{games_solo:12,wins_solo_normal:2,losses_solo_normal:1,wins_solo_insane:6,losses_solo_insane:3,games_kit_basic_solo_default:12},12);
assert.equal(sw.entries.length,5);assert.equal(sw.status,'results');assert.equal(sw.entries.find(e=>e.id==='solo_insane').games,9);
assert.deepStrictEqual(sw.entries.map(e=>e.label),['Mini SkyWars','Normal Solo','Normal Doubles','Insane Solo','Insane Doubles']);
assert.equal(sw.entries[0].games,0);
assert(b('BEDWARS',{},0).entries.every(e=>e.unavailableValue));
assert.equal(b('SKYWARS',{games_solo:12,wins_solo_normal:2,losses_solo_normal:1},12).entries.find(e=>e.id==='solo_unknown').games,9);
assert.equal(b('BEDWARS',{eight_one_games_played_bedwars:2},5).entries.find(e=>e.unknown).games,3);
assert.equal(b('BEDWARS',{eight_one_games_played_bedwars:8},5).status,'unavailable');
assert.equal(b('BEDWARS',{eight_one_games_played_bedwars:-2},5).status,'unavailable');
assert.equal(b('SKYWARS',{},0).status,'unavailable');
const lagged=b('SKYWARS',{games_team:2,wins_team_normal:2,losses_team_normal:1},3);
assert.equal(lagged.entries.find(e=>e.id==='team_normal').games,3,'lagging parent counts must not erase known Normal results');
assert.equal(lagged.entries.reduce((n,e)=>n+e.games,0),3,'parent and variant counters must not double-count matches');
assert.equal(b('SKYWARS',{games_team:2},2).entries.find(e=>e.id==='team_unknown').label,'Doubles (unspecified)','missing variants must remain explicit rather than guessed');
console.log('PASS mode counts: aggregate/kit/streak exclusion, child deduplication, results split, partial/missing/conflicting data');
