const DENICK_ISLAND_TOPPER_NAMES = [
    'Note',
    'Sheep',
    'Slime',
    'TNT',
    'Tree',
    'Flame',
    'Heart',
    'Candy Cane',
    'Fancy Santa Hat',
    'Bunch of Presents',
    'Comet the Reindeer',
    'Bunny',
    'Firework Rocket',
    'Fountain Firework',
    'Mark of the Paw',
    'Year of the Pig',
    'Sword',
    'Bomb',
    'Gong',
    'Smiley Face',
    'Rubix Cube',
    'Brick House',
    'Candle',
    'Ghost',
    'Sinister Pot',
    'Thunder',
    'Gargoyle',
    'Suspicious Tree',
    'Wicked Z-type',
    'Boo!',
    'Gravestone',
    "Witch's Potion",
    'Spooky Lantern',
    'Wingless Angel',
    'Robin',
    'Basket',
    'Carrot',
    'Easter Bell',
    'Yin and Yang',
    'Cherry Blossom',
    'Temple',
    'Lantern',
    'Candles',
    'Firecracker',
    'Assassin',
    'Shopping Cart',
    'Invisible Villager',
    'Snowflake',
    'Leaf',
    'Sapling',
    'Surfboard',
    'Wave',
    'Big Present',
    'Gingerbread House',
    'Stocking',
    'Pudding',
    'Tall Carrot',
    'Rain Cloud',
    'Sprout',
    'Watermelon',
    'Spooky Hypixel',
    'Pinecone',
    'Nest of Chicks',
    'Mister Egg',
    'Fishing Rod',
    'Bungalow',
    'Owl',
    'Birdhouse',
    'Picnic Basket',
    'Watering Can',
    'Rainbow Sheep',
    'Sunglasses',
    'Treasure Chest',
    'Fish Bowl',
    'Sloth',
    'Monocle',
    'Clown',
    'Happy Pumpkin',
    "Mini Herobrine's Mansion",
    'Candy Corn',
    'Candy Basket',
    'Frankenstein',
    'Mummy',
    'Devil',
    "Witch's House",
    'Magic Snowglobe',
    'Bell',
    'Penguin',
    'Easter Egg',
    'Rabbit Ears',
    'Chocolate Egg',
    'Sunflower',
    'Temple Hut',
    'Ox',
    'Red Envelope',
    'Gapple',
    'Skullsword',
    "Collector's Chest",
    'Toxic Rain',
    'Lazy Miner',
    'Dreidel',
    'Gold Present',
    'Penjing',
    'Tiger',
    'Ladybug',
    'Parasol',
    'Chocolate Bar',
    'Chimney',
    'Small Rabbit',
    'Cow',
    'Party Sloth',
    'Crab',
    'Eyeball',
    'Snowy Cabin',
    'Panda',
    'Pagoda',
    'Coconut Drink',
    'Cyclops',
    'Witch',
    'Hot Cocoa',
    'Roast Turkey',
    'Penguin Stack',
    'Snake',
    'Hermit Crab',
    'Sailboat',
    'Chicken',
    'Top Hat',
    'Whale',
    'Fancy Helmet',
    'Tournament Position',
    'Parchment the Skelly',
    'Witch Hat',
    'Skeleton Thumbs Up',
    'Werewolf',
    'Reaper',
    'L',
    'Humongous Christmas Tree',
    'Sleigh',
    'Snowman',
    'Hatching Egg',
    'Tulips',
    'Lunar Dragon',
    'Dragon Head',
    "Champion's Chalice",
    'Heartbleed',
    'Magic Bunny',
    'Ballista',
    'Traffic Light',
    "Assassin's Blade",
    'Presidential Goons',
    'Nutcracker',
    'Ramen',
    'Bee',
    'Bluebird',
    'Demon',
    'Zombie Hand',
    'Large Rabbit',
    'Hypixel Knight',
    'Sand Castle',
    'Chocolate Bunny',
    'Flamingo'
];

const DENICK_DEATH_CRY_NAMES = [
    'Bazinga',
    'Deflated Toy',
    'Enderman',
    'Dinosaur',
    'Robot Mouse',
    'Pig',
    'Grumpy Villager',
    'Sad Puppy',
    'Monster Burp',
    'Fireball',
    'Dry Bones',
    'Ding',
    'Splash',
    'Bat',
    'Plop',
    'Gone',
    'Burp',
    'Scurry',
    'Squeal',
    'Doused Lantern',
    'Cat',
    'Aww',
    'Energy',
    'Grumble',
    'Howl',
    'Sniff',
    'Squeak',
    'Firework',
    'Dragon Roar',
    'Sad Moo',
    "Ghost's Cry",
    'Arcade',
    'Miracle',
    'Rage',
    'Dark Portal',
    'Haunted Curse',
    'Guardian'
];

const DENICK_SHOPKEEPER_SKIN_NAMES = [
    'Blacksmith',
    'Skeleton',
    'Zombie Pigman',
    'Zombie',
    'Villager Zombie',
    'Wither Skeleton',
    'Blaze',
    'Bed Salesman',
    'Holiday Bartender',
    'Magic Vendor',
    'Chen',
    'Li',
    'Xiu',
    'Zhao',
    'Stellar',
    'Creeper',
    'Witch',
    'Bed Researcher',
    'King of Beds',
    'Snowman',
    'Bao',
    'Wei',
    'Egg Delivery',
    'Killer',
    'Cheesy',
    'Bunny Costume',
    'Present Man',
    'Blue Sheep Pajamas',
    'Purple Pig Pajamas',
    'Red Frog Pajamas',
    'Green Cow Pajamas',
    'Slumber Hotel Receptionist',
    'Frog Man',
    'Evil Eye',
    'Ender Pulse',
    'Santa',
    'Holiday Tree',
    'Lucky Cat',
    'Cute Puppy',
    'Enderman',
    'Mr. Giftman',
    'Mouse',
    'Bunny in a Suit',
    'Skeletor',
    'Watcher',
    'Upside Down Snowman',
    'Penguin',
    'Aqua Duck Pajamas',
    'Pink Bunny Pajamas',
    'Pink Rabbit',
    'Blue Rabbit',
    'Ghost',
    'Scarecrow',
    'Lumberjack',
    'Warrior',
    'Reindeer',
    'Grinch',
    'Bright Tiger',
    'Man Wearing Suit',
    'Ratman',
    'Spaceman',
    'Hammer',
    'Heatwave',
    'John Indigos',
    'Oasis Spirit',
    'Lester Brody',
    'Bundled Snowman',
    'Dark Dragon',
    'Ice Queen',
    'Astronaut',
    'Toonywise',
    'You!',
    'Quack',
    'Wither',
    'Rudolph',
    'Cluck Stack',
    'Dragon',
    'Sacred Cattle',
    'Defuser',
    'Marksman',
    'President Sloth',
    'Patriotic Eagle',
    'Merchant',
    'Elf with Snow Globe',
    'Gold Tiger',
    'Wither Tower'
];

const DENICK_GLYPH_NAMES = [
    'Iron',
    'Gold',
    'Diamond',
    'Emerald',
    'Thumbs Down',
    'Thumbs Up',
    'Hi',
    'Storm',
    'Sword',
    'Yes',
    'Burn',
    'Daisy',
    'No',
    'Bronze Shield',
    'Silver Shield',
    'Gold Shield',
    'Star',
    'Candy Cane',
    'Christmas Tree',
    'Gift',
    'Bunny',
    'Big Smile',
    'Chick',
    'Celebration Popper',
    'Lantern',
    'Pig',
    'Squeak',
    'Lion Dancer',
    'Bed',
    'GG',
    'Smiley Face',
    'Spectrum',
    'Lol',
    'TNT',
    'Ghostly Ghost',
    'Hall-o-ween',
    'Spider',
    'Evil Pumpkin',
    'Cute Pumpkin',
    'Grave',
    'Super Snow Golem',
    'Gingerbread Man',
    'Holly',
    'Bauble',
    'Pilgrim Hat',
    'Quack',
    'Bloom',
    'Bunny Guy',
    'Party',
    'Hot Cross Bun',
    'Easter Flower',
    'Carrot',
    'Blossom',
    'Orange',
    'Earth',
    'Sparkle',
    'Lunar Gold',
    'Lucky Rabbit',
    'Coconut',
    'Flame',
    'Shell',
    'Heart',
    'Angry Face',
    'Creeper Scream',
    'Skull',
    'Shock Face',
    'Winky Face',
    'Scream Face',
    'Bat',
    'Candy',
    'Eyeball',
    'Witch Hat',
    'Candy Corn',
    'Black Cat',
    'Cauldron',
    'Hype the Elf',
    'Santa Hat',
    'Dreidel',
    'Menorah',
    'Snowflake',
    'Festive Bell',
    'Easter Egg',
    'Chocolate Egg',
    'Egg Basket',
    'Rabbit',
    'Dog',
    'Dragon',
    'Rose',
    'Mouse',
    'Fai Chun',
    'Red Envelope',
    'Strawberry',
    'Palm Tree',
    'HOT',
    'Umbrella',
    'Cry Face',
    '#1',
    'RIP',
    'Chicken',
    'Rainbow',
    'Evil Kitty',
    'Very Evil Pumpkin',
    'Cute Ghost',
    'Reindeer',
    'Stocking',
    'Wreath',
    'Chocolate',
    'This is Fine',
    'Egg with Bow',
    'Sunflower',
    'Chinese Firecracker',
    'Moon',
    'Tiger',
    'Player Face'
];

const DENICK_FIGURINE_NAMES = [
    'Sky Island',
    'Grass Block',
    'Nether Portal',
    'Fireballs',
    'Sniper',
    'Diamonds',
    'Diamond Hoe',
    'Groopo',
    'Missing Bed',
    'Alchemy',
    'Shears',
    'Alex',
    'Crossed Swords',
    'Zombie',
    'Creeper',
    'Guardian',
    'Fishing Rod',
    'Housing',
    'Ender Pearl',
    'The Pit',
    'Golden Apple',
    'Bridge Egg',
    'Dante',
    'Hypixel Server',
    'The Delivery Man',
    'Hot Air Balloon',
    'Steve',
    'Sheep',
    'Don Espresso',
    'Sandman',
    'Tic Tac Toe',
    'Bed Defense',
    'Top Killer',
    'Iron Punch',
    'Iron Rose',
    'Emeralds',
    'TNT',
    'Hypixel',
    'Enderman',
    'Rezzus',
    'Blitz Star',
    'Hammer vs Heatwave',
    'Ratman in the City',
    'Magma Boss',
    'Cerberus',
    'Legacy Statues',
    'Bed Destroyer',
    'Knockback',
    'Dragon Slayer',
    'Build Battle',
    'Kart Racing',
    'Executives Meeting'
];

const DENICK_PROJECTILE_TRAIL_NAMES = [
    'Slime',
    'Ender',
    'Lava',
    'Potion',
    'Water',
    'Black Smoke',
    'White Smoke',
    'Notes',
    'Blue Dust',
    'Red Dust',
    'Purple Dust',
    'Cursed Flames',
    "Spider's Silk",
    'Lunar Dust',
    'The End',
    'Roses',
    'Fire',
    'Magic',
    'Green Star',
    'Angry Villager',
    'Firework',
    'Bone',
    'Pumpkin Pie',
    'Flame Rings',
    'Howling Wind',
    'Wisp Whirlwind',
    'Hoops',
    'Candy Basket',
    'Snowball Rain',
    'Hanukkah',
    'Rainy',
    'Spring Ribbons',
    'Rocket',
    'Let There Be Leather',
    'Ice Cold',
    'Portal',
    'Slumber',
    'Meteor Blaze',
    'Hearts',
    'Bloody',
    'Rainbow',
    'Bee',
    'Random',
    "Jack O' Lantern",
    'Icicle',
    'Fireball',
    'Sparkler',
    'Fanged',
    'DNA',
    'Wingman',
    'Twisted',
    'Trick or Treat',
    'Pumpkin Volley',
    'Magic Wind',
    'Merry',
    'Tinsel',
    'Present',
    'Peep!',
    'Twin Dragon',
    'Cheese',
    'Fire Spiral',
    'Bite',
    'Stormy',
    'Twirling Snowflakes'
];

module.exports = {
    DENICK_ISLAND_TOPPER_NAMES,
    DENICK_DEATH_CRY_NAMES,
    DENICK_SHOPKEEPER_SKIN_NAMES,
    DENICK_GLYPH_NAMES,
    DENICK_FIGURINE_NAMES,
    DENICK_PROJECTILE_TRAIL_NAMES
};
