'use strict';
const fs=require('fs'),path=require('path');
function writeGallery(directory){
    const views=[['dashboard','Dashboard'],['proxy-running','Proxy running'],['notifications','Notifications'],['sidebar-collapsed','Collapsed sidebar'],['global-search','Global search'],['overlay-columns','Overlay columns'],['overlay-16-1440','Overlay — 16 players'],['overlay-16-1024','Overlay — minimum window'],['sessions','Session history and card'],['session-card','Exported session PNG'],['local-session','Session with API off'],['local-session-card','Exported local session PNG'],['nicks-saved-matches','Nicks — saved matches'],['nicks-lookup','Nicks — lookup'],['nicks-manual-mapping','Nicks — manual mapping'],['reminders','Account reminders'],['profiles','Profiles'],['profile-details','Profile details'],['profile-editor','Profile editor'],['settings-launcher','Appearance'],['settings-scan','Scanning and sharing'],['settings-gameplay','Automation'],['settings-sessions','Sessions and recaps'],['settings-denick','Nicknames'],['settings-overlay','Overlay and chat'],['settings-display','Tab-list editor'],['settings-nametags','Nametags'],['settings-colors','Names and colors'],['settings-api','API keys'],['settings-network','Proxy and network'],['console','Console logs'],['account-menu','Account menu'],['account-manager','Account manager'],['account-signin','Microsoft sign-in']].filter(([name])=>fs.existsSync(path.join(directory,`${name}.png`)));
    function collect(folder='') {
        for (const entry of fs.readdirSync(path.join(directory,folder),{withFileTypes:true})) {
            const relative=folder?folder+'/'+entry.name:entry.name;
            if(entry.isDirectory())collect(relative);
            else if(entry.name.endsWith('.png')&&!['gallery-preview.png','failure.png'].includes(entry.name)) {
                const name=relative.slice(0,-4);
                if(!views.some(view=>view[0]===name))views.push([name,name.replaceAll('/',' / ').replaceAll('-',' ')]);
            }
        }
    }
    collect();
    fs.writeFileSync(path.join(directory,'gallery.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fury — implemented launcher</title><style>*{box-sizing:border-box}body{margin:0;background:#101316;color:#f1f3f5;font:14px system-ui;display:grid;grid-template-columns:235px 1fr;height:100vh}aside{padding:24px 16px;overflow:auto;border-right:1px solid #303840}h1{font-size:19px;margin:0 0 8px}aside p{font-size:12px;line-height:1.5;color:#a1aab5;margin-bottom:24px}button{display:block;width:100%;text-align:left;padding:10px;border:0;background:none;color:inherit;border-radius:6px;cursor:pointer;font:inherit;font-size:12px}button.active{background:#f3c64e20;color:#f3c64e}button:hover{background:#ffffff0d}main{padding:24px;min-width:0;overflow:auto}h2{font-size:20px;margin:0 0 8px}main p{color:#a1aab5;font-size:12px}figure{margin:20px 0;display:flex;justify-content:center;align-items:flex-start;border:1px solid #303840;background:#191d21;border-radius:8px;overflow:hidden}img{max-width:100%;height:auto;display:block}a{color:#f3c64e}@media(max-width:750px){body{grid-template-columns:170px 1fr}aside,main{padding:12px}}</style><aside><h1>FURY / Implementation</h1><p>Actual Electron screenshots using an isolated test profile. Offline skin fallbacks and fixture statistics are shown.</p><nav></nav></aside><main><h2></h2><p>Reference design: revision 2 · <a href="verification.json">Verification results</a></p><figure><img alt=""></figure><a id="full" target="_blank">Open full-size image</a></main><script>const views=${JSON.stringify(views)};const nav=document.querySelector('nav');function select(index){const[name,title]=views[index];document.querySelector('h2').textContent=title;const img=document.querySelector('img');img.src=name+'.png';img.alt=title;document.querySelector('#full').href=img.src;[...nav.children].forEach((b,i)=>b.classList.toggle('active',i===index));}views.forEach(([,title],i)=>{const b=document.createElement('button');b.textContent=title;b.onclick=()=>select(i);nav.append(b)});select(0);</script></html>`,'utf8');
    return views.length;
}
module.exports={writeGallery};
if(require.main===module)writeGallery(path.resolve(__dirname,'../output/launcher-redesign-implemented'));
