'use strict';
const assert=require('assert'),path=require('path');
module.exports=async function verifySessionSettings({page,output}) {
    await page.evaluate("activatePage('settings');activateSettingsSubpage('sessions',false)");
    assert(await page.$eval('#replay-details-module',e=>!e.closest('.fury-removed')&&e.getBoundingClientRect().height>0),'Replay Menu toggle is shown on the Sessions page');
    assert.strictEqual(await page.$('.fury-session-goals, .session-goal-settings, [id^="session-goal-"]'),null);
    assert.strictEqual(await page.$('#session-boundary-minutes'),null);
    assert.strictEqual(await page.$('#session-retention'),null);
    assert.deepStrictEqual(await page.evaluate('({boundary:state.settings.features.sessionBoundaryMinutes,retention:state.settings.features.sessionRetention})'),{boundary:30,retention:0});
    const choose=async style=>{
        await page.locator(`.fury-recap-tabs [data-style="${style}"]`).click();
        await page.waitForFunction(style=>state.settings.features.sessionRecapStyle===style,{},style);
    };
    await choose('compact');
    assert(await page.$eval('#session-recap-fields',e=>e.closest('.session-field-section').hidden));
    assert(!(await page.$eval('#session-recap-preview',e=>e.textContent.includes('Session:'))));
    await choose('custom');
    assert(await page.$eval('#session-recap-fields .fury-chip-label',e=>{
        const luminance=color=>color.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=0.04045?v/12.92:((v+0.055)/1.055)**2.4).reduce((sum,v,i)=>sum+v*[0.2126,0.7152,0.0722][i],0);
        const fg=luminance(getComputedStyle(e).color),bg=luminance(getComputedStyle(e.closest('.fury-chip')).backgroundColor);
        return (Math.max(fg,bg)+0.05)/(Math.min(fg,bg)+0.05)>=4.5;
    }),'Selected chips keep readable contrast');
    assert(!(await page.$eval('#session-recap-fields',e=>e.closest('.session-field-section').hidden)));
    const recap='.fury-binary-choice:has(#game-recap-enabled)';
    await page.locator(recap+' .fury-binary-off').click();
    await page.waitForFunction('state.settings.features.gameRecapEnabled===false');
    assert.strictEqual(await page.$eval('.session-recap-preview-shell',e=>getComputedStyle(e).display),'none');
    await page.locator(recap+' .fury-binary-on').click();
    await page.waitForFunction('state.settings.features.gameRecapEnabled===true');
    assert.strictEqual(await page.$eval('#session-recap-style',e=>e.value),'custom');
    await page.waitForSelector('.fury-session-preview-section canvas');
    const storedBefore=await page.evaluate('JSON.stringify(state.sessionHistory.sessions)');
    const chartOption='#session-bedwars-fields label:has(input[value="gamesByMode"])';
    assert(await page.$eval(chartOption,e=>e.querySelector('input').checked),'Existing settings keep the chart enabled');
    const chartWidth=await page.$eval('.fury-session-preview-section canvas',e=>e.width);
    await page.locator(chartOption).click();
    await page.waitForFunction('state.settings.features.sessionBedwarsFields.includes("hideGamesByMode")');
    await page.waitForFunction(()=>{const c=document.querySelector('.fury-session-preview-section canvas');return c&&!c.getAttribute('aria-label').includes('Games by mode');});
    assert(await page.$eval('.fury-session-preview-section canvas',e=>e.width)<chartWidth,'Chart off reclaims its space');
    await page.evaluate('refresh()');
    assert(!(await page.$eval(chartOption,e=>e.querySelector('input').checked)),'Chart preference survives reload');
    assert(await page.$eval('#session-skywars-fields input[value="gamesByMode"]',e=>e.checked),'Other games keep their own chart preference');
    await page.evaluate("activatePage('sessions');document.querySelector('.fury-session-row').open=true");
    await page.waitForSelector('.fury-card-image canvas');
    assert(!(await page.$eval('.fury-card-image canvas',e=>e.getAttribute('aria-label').includes('Games by mode'))),'Existing card respects the chart toggle');
    assert.strictEqual(await page.evaluate('JSON.stringify(state.sessionHistory.sessions)'),storedBefore);
    await page.evaluate("activatePage('settings');activateSettingsSubpage('sessions',false)");
    await page.locator(chartOption).click();
    await page.waitForFunction('state.settings.features.sessionBedwarsFields.includes("gamesByMode") && !state.settings.features.sessionBedwarsFields.includes("hideGamesByMode")');
    await page.waitForFunction(()=>document.querySelector('.fury-session-preview-section canvas')?.getAttribute('aria-label').includes('Games by mode'));

    const deaths='#session-bedwars-fields input[value="deaths"]';
    assert(await page.$eval(deaths,e=>e.checked));
    await page.locator('#session-bedwars-fields label:has(input[value="deaths"])').click();
    await page.waitForFunction('!state.settings.features.sessionBedwarsFields.includes("deaths")');
    await page.waitForFunction(()=>!document.querySelector('.fury-session-preview-section canvas')?.getAttribute('aria-label').includes('Deaths: 31'));
    await page.evaluate('refresh()');
    assert(!(await page.$eval(deaths,e=>e.checked)),'Appearance survives a settings reload');
    await page.evaluate("activatePage('sessions');document.querySelector('.fury-session-row').open=true");
    await page.waitForSelector('.fury-card-image canvas');
    assert(!(await page.$eval('.fury-card-image canvas',e=>e.getAttribute('aria-label').includes('Deaths: 31'))),'Existing saved card uses the new appearance');
    assert.strictEqual(await page.evaluate('JSON.stringify(state.sessionHistory.sessions)'),storedBefore,'Appearance must not modify saved session stats');
    await page.evaluate("activatePage('settings');activateSettingsSubpage('sessions',false)");
    await page.locator('#session-bedwars-fields label:has(input[value="deaths"])').click();
    await page.waitForFunction('state.settings.features.sessionBedwarsFields.includes("deaths")');
    await page.waitForFunction(()=>document.querySelector('.fury-session-preview-section canvas')?.getAttribute('aria-label').includes('Deaths: 31'));
    await page.locator('.fury-field-tabs [data-mode="SKYWARS"]').click();
    assert(await page.$eval('#session-bedwars-fields',e=>e.parentElement.hidden));
    assert(!(await page.$eval('#session-skywars-fields',e=>e.parentElement.hidden)));
    assert(await page.$eval('.fury-settings-card-preview',e=>e.textContent.includes('Your next SkyWars')));
    await page.locator('.fury-field-tabs [data-mode="BEDWARS"]').click();
    await page.waitForSelector('.fury-session-preview-section canvas');
    for(const width of [1440,1024]) {
        await page.setViewport({width,height:900,deviceScaleFactor:1});
        await page.evaluate(()=>{document.querySelectorAll('.notification-close').forEach(b=>b.click());document.querySelector('main').scrollTop=0;});
        await page.screenshot({path:path.join(output,`sessions-redesign-${width}-top.png`)});
        await page.$eval('.fury-session-appearance',e=>e.scrollIntoView({block:'start'}));
        await page.screenshot({path:path.join(output,`sessions-redesign-${width}-appearance.png`)});
        const overflow=await page.evaluate(()=>[...document.querySelectorAll('[data-settings-subpage="sessions"] button,[data-settings-subpage="sessions"] .fury-chip,[data-settings-subpage="sessions"] canvas')].filter(e=>e.getClientRects().length).filter(e=>{const r=e.getBoundingClientRect();return r.right>innerWidth||r.left<0;}).map(e=>e.textContent));
        assert.deepStrictEqual(overflow,[],`Session controls fit ${width}px`);
    }
    console.log('PASS Session settings: fixed lifecycle, conditional recap controls, persisted appearance updates old cards without changing stats, real preview, game tabs, responsive layouts');
};
