'use strict';
const fs=require('fs'),assert=require('assert'),puppeteer=require('puppeteer');
const source=fs.readFileSync('src/launcher/renderer/launcher_redesign.js','utf8');
const render=source.slice(source.indexOf('function renderSessions('),source.indexOf("const consoleTabs=$('[data-page=\"console\"]"));
(async()=>{const browser=await puppeteer.launch({headless:true});try{const page=await browser.newPage();await page.setContent('<button id="sessions-start-new"></button><button id="sessions-end-current"></button><div id="session-history-list"></div>');
await page.evaluate(render=>{
const RealDate=Date;window.dayOffset=0;window.Date=class extends RealDate {constructor(...args){super(...(args.length?args:[RealDate.now()+window.dayOffset*86400000]));}};
const $=s=>document.querySelector(s),escape=s=>String(s),svg=()=>'';
const node=(tag,cls,html='')=>{const e=document.createElement(tag);e.className=cls;e.innerHTML=html;return e;};
const button=(html,fn,cls='')=>{const e=node('button',cls,html);e.addEventListener('click',fn);return e;};
const getState=()=>({viewedAccount:{key:'test',name:'Player'},proxyHealth:{connectedAccount:'Player'}});
const cards={date:s=>String(s),time:()=>'',duration:()=>''};
let sessionsKey='',sessionsDay='',cardGeneration=0;const cardsById=new Map(),openSessionCards=new Map();
window.generated=0;
const makePreview=(session,host)=>{window.generated++;host.append(node('canvas',''));};
const notify=()=>{},invoke=async()=>({ok:true}),refresh=async()=>{};
eval(render);
window.historyFixture={sessions:Array.from({length:1500},(_,i)=>({id:String(i),name:'Player',startedAt:i,endedAt:i+1,modes:[{mode:'BEDWARS',label:'Bedwars',wins:1,losses:0}]}))};
window.updateSessions=()=>renderSessions(window.historyFixture,{});window.updateSessions();
},render);
assert.equal(await page.evaluate('generated'),0,'Collapsed history must not render images');
await page.evaluate(()=>{const rows=document.querySelectorAll('details');window.firstRow=rows[0];rows[0].open=true;rows[1].open=true;});await page.waitForFunction('generated===2');
await page.evaluate(()=>{document.querySelectorAll('details')[1].open=false;});await page.waitForFunction(()=>!document.querySelectorAll('details')[1].open);await new Promise(r=>setTimeout(r,50));
await page.evaluate(()=>{dayOffset=1;updateSessions();});assert.equal(await page.evaluate('generated'),3,'Only open card should regenerate on a new day');assert(await page.evaluate('firstRow===document.querySelector("details")'),'Day rollover must preserve list DOM');
await page.evaluate(()=>{updateSessions();updateSessions();});assert.equal(await page.evaluate('generated'),3,'Same-day refresh must reuse previews');
await page.evaluate(()=>{document.querySelectorAll('details')[1].open=true;});await page.waitForFunction('generated===4');
await page.evaluate(()=>{document.querySelectorAll('details')[1499].open=true;});await page.waitForFunction('generated===5');
await page.evaluate(()=>{historyFixture.sessions[0].games=[{id:'verification-update'}];historyFixture.sessions[5].modes[0].wins++;updateSessions();});
assert.equal(await page.evaluate('generated'),5,'metadata and another session must not regenerate the open card');
assert(await page.evaluate('firstRow===document.querySelector("details")'),'polling must preserve row identity');
await page.evaluate(()=>{historyFixture.sessions[0].modes[0].wins++;updateSessions();});
assert.equal(await page.evaluate('generated'),6,'changed card stats still refresh');
assert(await page.evaluate('firstRow===document.querySelector("details")'),'live stat changes must preserve row identity');
console.log('PASS 1,500 sessions: zero initial card renders, only open cards refresh daily, DOM retained, closed cards refresh lazily, same-day cache reused.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
