const fs=require('fs'),assert=require('assert'),path=require('path'),puppeteer=require('puppeteer');
const format=require('../src/launcher/renderer/launcher_denick_format');
const {lookupPlayerStats}=require('../src/stats/denickLookupPlayer');
assert.equal(lookupPlayerStats({stats:{Bedwars:{beds_broken_bedwars:24,beds_lost_bedwars:6}}}).bblr,4);
assert.equal(lookupPlayerStats({stats:{Bedwars:{beds_broken_bedwars:24}}}).bblr,24);
const html=fs.readFileSync('launcher.html','utf8');
const render=html.slice(html.indexOf('function renderDenickLookupResults('),html.indexOf('async function runDenickLookup()'));
const rows=[{name:'Nestersen',rankPrefix:'§6[MVP§0++§6]',nameColor:'§6',star:1911,finals:53180,beds:24333,fkdr:11.21,bblr:4.09,wins:18199,losses:4486,wlr:4.06,winstreak:9},{name:'LongestPlayerIGN',rankPrefix:'§b[MVP§c+§b]',star:12345,finals:123456789,beds:999999,fkdr:123.45,bblr:42,wins:99999,losses:1234,wlr:81.03,winstreak:null},{name:'Short',star:1,finals:1,beds:0,fkdr:0,bblr:null,wins:1,losses:0,wlr:1,winstreak:0}];
for(const row of rows)row.identityHtml=format.identity(row,row.name);
const values={};for(const row of rows)for(const key of ['finals','beds','fkdr','bblr','wins','losses','wlr','winstreak'])values[key+':'+row[key]]=format.statValue(key,row[key],['fkdr','bblr','wlr'].includes(key));
(async()=>{const browser=await puppeteer.launch({headless:true});try{const page=await browser.newPage();await page.setContent('<html class="fury-redesign"><head>'+[...html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)].map(m=>m[0]).join('')+'</head><body style="display:block;padding:12px"><div class="denicks-page"><span id="denick-lookup-count"></span><div id="denick-lookup-results"></div></div></body></html>');for(const css of ['src/launcher/styles/launcher_theme.css','src/launcher/styles/launcher_accessibility.css','src/launcher/styles/launcher_windows_design.css','src/launcher/styles/launcher_windows_settings.css','src/launcher/styles/launcher_redesign.css','src/launcher/styles/launcher_settings_refinement.css'])await page.addStyleTag({path:path.resolve(css)});
await page.addStyleTag({content:'.denick-skin-head { background-image:url(data:image/png;base64,'+fs.readFileSync('assets/default-skin.png').toString('base64')+'); }'});
await page.evaluate(({render,rows,values})=>{window.escapeHtml=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');window.cosmeticLabelPairs=()=>'';window.denickFormat={identity:row=>row.identityHtml,statValue:(key,value)=>values[key+':'+value]};eval(render);renderDenickLookupResults({candidates:rows},{finals:53180,beds:24333});},{render,rows,values});
for(const width of [1440,1060,1024,680]){await page.setViewport({width,height:400});const measures=await page.$$eval('.denick-result-row',els=>els.map(el=>{const rect=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};};return {card:rect(el),head:rect(el.querySelector('.denick-skin-head')),copy:rect(el.querySelector('.denick-lookup-copy')),identity:[...el.querySelector('.denick-formatted-identity').children].map(rect),stats:[...el.querySelectorAll('.denick-result-stat')].map(s=>({label:rect(s.querySelector('.denick-stat-label')),value:rect(s.querySelector('strong'))}))};}));for(const row of measures){const y=row.identity[0].y;const center=r=>r.y+r.h/2;assert(Math.abs(center(row.head)-center(row.card))<.5,'Head must center in card');assert(Math.abs(center(row.identity[0])-center(row.head))<.5,'Identity must center against head');assert(Math.abs(center(row.copy)-center(row.head))<.5,'Copy must center against head');for(const identity of row.identity)assert(Math.abs(identity.y-y)<.5,JSON.stringify(row));for(const stat of row.stats){assert(Math.abs(stat.value.y-y)<.5,JSON.stringify(row));assert(Math.abs(stat.value.x+stat.value.w/2-stat.label.x-stat.label.w/2)<.5,JSON.stringify(stat));}}for(let i=1;i<measures.length;i++)for(let s=0;s<8;s++)assert(Math.abs(measures[0].stats[s].label.x-measures[i].stats[s].label.x)<.5);fs.mkdirSync('output/lookup-aligned',{recursive:true});await page.screenshot({path:`output/lookup-aligned/${width}.png`});console.log('PASS head/value/card vertical centers, symmetric spacing, header centering, cross-row columns at '+width);}
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
